### ISSUE TITLE
fuente debería ser "Times New Roman"

### ISSUE THREAD

**Issue by rmujica** [Autopawn/tex-thesis-template#1]
Hola! Primero quiero agradecerte por este aporte, estoy seguro que somos muchos los que utilizaremos este template.

Quería comentarte que según la normativa interna del departamento [MemoriasNormasInternasdeIngenieria2008.pdf](https://github.com/Autopawn/tex-thesis-template/files/1262358/MemoriasNormasInternasdeIngenieria2008.pdf) (lo subió el profe Solar al curso de Seminario de Memoria en Campus Santiago) , se debe usar "Times New Roman", o en su defecto una tipografía serif. Esto sale en la sección 4 del documento que adjunto.

Haría un pull request yo mismo pero en estos momentos no puedo, apenas pueda lo haré.

Gracias!

**Comment by autopawn** [comment]
Hola,

El profesor Luís Hevia me dijo que la nueva planilla se debía hacer en __Calibri__, como es una fuente privativa se está usando la versión libre llamada __Carlito__, de cualquier manera, por ahora se puede cambiar la *font* utilizada reemplazando __Carlito__ en las líneas que aparece en `main.tex` por la *font* que corresponda.

```
\setmainfont{Carlito}
...
\renewcommand{\cftsecfont}{\fontsize{12}{14}\selectfont\fontspec{Carlito}}
\renewcommand{\cftsubsecfont}{\fontsize{12}{14}\selectfont\fontspec{Carlito}}
\renewcommand{\cftsubsubsecfont}{\fontsize{12}{14}\selectfont\fontspec{Carlito}}

\renewcommand\cftfigfont{\fontsize{12}{14}\selectfont\fontspec{Carlito}}
```

Consultaré con el profesor Hevia sobre esto antes de realizar cambios.

Saludos.

**Comment by autopawn** [comment]
El profesor me respondió que ahora se está en proceso de cambiar __Times New Roman__ de las memorias por __Calibri__ o similar.
