### ISSUE TITLE
El font de Carlito en negrita y cursiva no son reconocidos

### ISSUE THREAD

**Issue by anibalbastiass** [Autopawn/tex-thesis-template#5]
Usando este template, segui las instrucciones descargando el Font de `Carlito` y al intentar poner en negrita o cursiva los textos (`\textbf{"Texto"}` o `\textit{"Texto"}`), no funcionaba. 

Para eso, tuve que agregar las siguientes lineas en el archivo `main.tex` (los agregue en la linea 202)

```latex
\setmainfont{Carlito}[BoldFont={* Bold}]
\setmainfont{Carlito}[ItalicFont={* Italic}]
```

Estos son los antecedentes de mi maquina:

```
PC: Macbook Pro 2020 M1
OS: MacOS BigSur 11.5.1
Latex Lib: LaTeXiT
IDE: Texpad 1.9.2
```

¿Será necesario enviar un Pull request para esto? Saludos

**Comment by autopawn** [comment]
Agregué los comandos sugeridos en el main. Luego de
```
\usepackage{fontspec}
```

Aunque no recuerdo que haya faltado Carlito en negritas o cursiva en mi sistema.

**Comment by anibalbastiass** [comment]
Buenisima, muchas gracias!
Otro comentario, tambien agregue el siguiente codigo para agregar subsecciones sin enumeración. Lo use para la sección de "Introducción", se llama `secnumberlesssubsection`

```latex
\newcommand{\secnumberlesssubsection}[1]{
\subsection*{#1}
\phantomsection
\addcontentsline{toc}{subsection}{#1}
\setcounter{subsection}{0}
}
```

Este es un ejemplo 

```latex
\secnumberlesssubsection{"Sub seccion sin enumeración"}
```

**Comment by anibalbastiass** [comment]
Gracias @autopawn por agregar las sugerencias. Cerraré este issue. Saludos.
